// <auto-generated />
using Lab1.db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lab1.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20200324094948_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Lab1.dto.CPUDto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CpuTypes")
                        .HasColumnType("int");

                    b.Property<int>("UsingPover")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("cPUDtos");
                });

            modelBuilder.Entity("Lab1.dto.MotherboardDto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CPUTypes")
                        .HasColumnType("int");

                    b.Property<int>("UsingPover")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("motherboardDtos");
                });

            modelBuilder.Entity("Lab1.dto.PowerSupplyDto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("UsingPover")
                        .HasColumnType("int");

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("powerSupplyDtos");
                });

            modelBuilder.Entity("Lab1.dto.RAMDto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("RAMTypes")
                        .HasColumnType("int");

                    b.Property<int>("UsingPover")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("rAMDtos");
                });

            modelBuilder.Entity("Lab1.dto.SystemUnitDto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("MaxPoverSupplyVolume")
                        .HasColumnType("int");

                    b.Property<int>("MotherboardTypes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.ToTable("systemUnitDtos");
                });
#pragma warning restore 612, 618
        }
    }
}
